### ISSUE TITLE
Error while setting up hf_weather platform for weather

### ISSUE THREAD

**Issue by georgewu57** [shaonianzhentan/hf_weather#5]
HA环境：
设备：N1
系统：openwrt_s905d_n1_R22.3.13_k5.4.184-flippy-70+o
安装方式：Docker安装的"homeassistant core"
HA版本：Home Assistant 2022.4.2

`Error while setting up hf_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hf_weather/weather.py", line 85, in async_setup_entry
    await data.async_update(dt_util.now())
  File "/config/custom_components/hf_weather/weather.py", line 413, in async_update
    [forec_cond[6], int(datemsg[6]["tmp"]["max"]), int(datemsg[6]["tmp"]["min"]), datemsg[6]["date"], datemsg[6]["pcpn"], datemsg[6]["pop"], datemsg[6]["cond"]["txt_d"]]
IndexError: list index out of range`

我在集成里面配置成功后，日志里出现了这样的错误，请问应该怎么修复呢？

**Comment by shaonianzhentan** [comment]
应该是密钥不对，请申请并自行测试密钥的正确性

**Comment by georgewu57** [comment]
会成功的,现在我国在这方面还是处于初级阶段的 机会还是很多的,而且有些并不需要多少专业技术,门槛并不高的,大家不要怕,根据自己的时间情况定位个适合自己的网上创业之路 !
如果您有兴趣的话，详情请登陆招聘网站:http://mcglotvzdh.cn/
